USE [master]
GO

/****** Object:  Database [DDACTS]    Script Date: 12/11/2014 17:21:12 ******/
CREATE DATABASE [DDACTS] ON  PRIMARY
( NAME = N'DDACTS', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\DDACTS.mdf' , SIZE = 2048KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
( NAME = N'Crash_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\DDACTS.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DDACTS] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DDACTS].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DDACTS] SET ANSI_NULL_DEFAULT OFF
GO

ALTER DATABASE [DDACTS] SET ANSI_NULLS OFF
GO

ALTER DATABASE [DDACTS] SET ANSI_PADDING OFF
GO

ALTER DATABASE [DDACTS] SET ANSI_WARNINGS OFF
GO

ALTER DATABASE [DDACTS] SET ARITHABORT OFF
GO

ALTER DATABASE [DDACTS] SET AUTO_CLOSE OFF
GO

ALTER DATABASE [DDACTS] SET AUTO_CREATE_STATISTICS ON
GO

ALTER DATABASE [DDACTS] SET AUTO_SHRINK OFF
GO

ALTER DATABASE [DDACTS] SET AUTO_UPDATE_STATISTICS ON
GO

ALTER DATABASE [DDACTS] SET CURSOR_CLOSE_ON_COMMIT OFF
GO

ALTER DATABASE [DDACTS] SET CURSOR_DEFAULT  GLOBAL
GO

ALTER DATABASE [DDACTS] SET CONCAT_NULL_YIELDS_NULL OFF
GO

ALTER DATABASE [DDACTS] SET NUMERIC_ROUNDABORT OFF
GO

ALTER DATABASE [DDACTS] SET QUOTED_IDENTIFIER OFF
GO

ALTER DATABASE [DDACTS] SET RECURSIVE_TRIGGERS OFF
GO

ALTER DATABASE [DDACTS] SET  DISABLE_BROKER
GO

ALTER DATABASE [DDACTS] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO

ALTER DATABASE [DDACTS] SET DATE_CORRELATION_OPTIMIZATION OFF
GO

ALTER DATABASE [DDACTS] SET TRUSTWORTHY OFF
GO

ALTER DATABASE [DDACTS] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO

ALTER DATABASE [DDACTS] SET PARAMETERIZATION SIMPLE
GO

ALTER DATABASE [DDACTS] SET READ_COMMITTED_SNAPSHOT OFF
GO

ALTER DATABASE [DDACTS] SET HONOR_BROKER_PRIORITY OFF
GO

ALTER DATABASE [DDACTS] SET  READ_WRITE
GO

ALTER DATABASE [DDACTS] SET RECOVERY SIMPLE
GO

ALTER DATABASE [DDACTS] SET  MULTI_USER
GO

ALTER DATABASE [DDACTS] SET PAGE_VERIFY CHECKSUM
GO

ALTER DATABASE [DDACTS] SET DB_CHAINING OFF
GO
